// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:dumbdumb_flutter_app/app/core/enums.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Unified method to access FirebaseOptions based on the [EnvironmentType]
  static FirebaseOptions currentPlatform(EnvironmentType type) {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _androidOption(type);
      case TargetPlatform.iOS:
        return _iOSOption(type);
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions _androidOption(EnvironmentType type) {
    switch (type) {
      case EnvironmentType.production:
        return android;
      case EnvironmentType.staging:
        return androidStaging;
      case EnvironmentType.development:
        return androidDev;
      default:
        return android;
    }
  }

  /// Firebase Configuration data
  /// To be update with your own project configuration data
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzE4rPFajLcoDnU206qN4FCH-r1eQlSio',
    appId: '1:810536580213:android:efa70204a6ce51fa04b43c',
    messagingSenderId: '810536580213',
    // project number
    projectId: 'dumbdumbflutter',
    storageBucket: 'dumbdumbflutter.appspot.com',
  );

  static const FirebaseOptions androidStaging = FirebaseOptions(
    apiKey: 'AIzaSyDzE4rPFajLcoDnU206qN4FCH-r1eQlSio',
    appId: '1:810536580213:android:2fc3957d9a31b1d404b43c',
    messagingSenderId: '810536580213',
    // project number
    projectId: 'dumbdumbflutter',
    storageBucket: 'dumbdumbflutter.appspot.com',
  );

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyDzE4rPFajLcoDnU206qN4FCH-r1eQlSio',
    appId: '1:810536580213:android:2fc3957d9a31b1d404b43c',
    messagingSenderId: '810536580213',
    // project number
    projectId: 'dumbdumbflutter',
    storageBucket: 'dumbdumbflutter.appspot.com',
  );

  static FirebaseOptions _iOSOption(EnvironmentType type) {
    switch (type) {
      case EnvironmentType.production:
        return ios;
      case EnvironmentType.staging:
        return iosStaging;
      case EnvironmentType.development:
        return iosDev;
      default:
        return ios;
    }
  }

  /// Firebase Configuration data
  /// To be update with your own project configuration data
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API KEY',
    appId: 'YOUR_API_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR STORAGE BUCKET',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );

  /// Firebase Configuration data
  /// To be update with your own project configuration data
  static const FirebaseOptions iosStaging = FirebaseOptions(
    apiKey: 'YOUR_API KEY',
    appId: 'YOUR_API_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR STORAGE BUCKET',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );

  /// Firebase Configuration data
  /// To be update with your own project configuration data
  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'YOUR_API KEY',
    appId: 'YOUR_API_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR STORAGE BUCKET',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );
}
